### ISSUE TITLE
Setup develop environment

### ISSUE THREAD

**Issue by streamwest-1629** [streamwest-1629/exec-onchanges#1]
# Todo

- [ ] Add Issue template
- [ ] Add Pull request template
- [ ] Add Golang development container
